vulnerability_id: CVE-2015-3206
notes:
- links: []
  text: The checkPassword function in python-kerberos does not authenticate the KDC
    it attempts to communicate with, which allows remote attackers to cause a denial
    of service (bad response), or have other unspecified impact by performing a man-in-the-middle
    attack.
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: 02d13860b25fab58e739f0e000bed0067b7c6f9c
    repository: https://github.com/02strich/pykerberos
