vulnerability_id: CVE-2020-29651
notes:
- links:
  - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-29651
  - https://github.com/pytest-dev/py/issues/256
  - https://github.com/pytest-dev/py/pull/257
  text: A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: 4a9017dc6199d2a564b6e4b0aa39d6d8870e4144
    repository: https://github.com/pytest-dev/py
